A, B, C = map(float, input().split())
print(f'TRIANGULO: {(A*C)/2:.3f}')
print(f'CIRCULO: {(C**2)*3.14159:.3f}')
print(f'TRAPEZIO: {(A+B)*C/2:.3f}')
print(f'QUADRADO: {B*B:.3f}')
print(f'RETANGULO: {A*B:.3f}')